version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - gosec
    - staticcheck
    - errcheck
    - unused
    - gocyclo
    - whitespace
    - lll
    - goconst
    - misspell
    - bodyclose
    - unconvert
    - ineffassign
    - gocritic
    - prealloc

  settings:
    gocyclo:
      min-complexity: 10
    lll:
      line-length: 88
      tab-width: 1
    misspell:
      locale: UK

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
