version: "2"

run:
  timeout: 5m
  tests: true
  concurrency: 4
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - gosec
    - staticcheck
    - errcheck
    - unused
    - gocyclo
    - whitespace
    - lll
    - goconst
    - misspell
    - bodyclose
    - unconvert
    - ineffassign
    - gocritic
    - prealloc
    - funlen
    - nakedret
    - dupl
    - errname
    - gocognit
    - revive

  settings:
    gocyclo:
      min-complexity: 10

    lll:
      line-length: 88
      tab-width: 1

    misspell:
      locale: UK

    funlen:
      lines: 50
      statements: 20
      ignore-comments: true

    goconst:
      min-len: 3
      min-occurrences: 2

    dupl:
      threshold: 100

    gocognit:
      min-complexity: 10

    revive:
      max-open-files: 2048
      severity: error
      enable-all-rules: false
      confidence: 0.1

      rules:
        - name: argument-limit
          arguments: [4]

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/GenesisEducationKyiv/software-engineering-school-5-0-Van4ooo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
