repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint
        entry: golangci-lint run --fix --config=.golangci.yml
        language: system
        types: [go]