name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  WEATHER_API_KEY: ${{ vars.WEATHER_API_KEY }}

jobs:
  build-and-test:
    name: Build, fmt-check & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22.x, ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify gofmt formatting
        run: |
          echo "Checking code formatting with gofmt..."
          
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files are not formatted:"
            echo "$UNFORMATTED"
            echo "::error ::Please run 'gofmt -w .' and commit the changes."
            exit 1
          fi

      - name: Run tests
        run: |
          echo "Running tests..."
          go test ./... -v
