name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-go-and-checkout@v1
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          args: --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      WEATHER_API_KEY: ${{ vars.WEATHER_API_KEY }}
    steps:
      - uses: ./.github/actions/setup-go-and-checkout@v1
      - name: Run tests
        run: go test -cover ./... -v

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-go-and-checkout@v1
      - name: Build project
        run: go build ./...
